name: Prod Deploy Serverless
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: dev-deploy-serverless.yaml

      - name: Setup Twilio CLI and promote environment
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
        run: cat service-sid/service-sid.txt && export TWILIO_FUNCTIONS_SERVICE_SID=$(cat service-sid/service-sid.txt) && npm install -g twilio-cli && twilio plugins:install @twilio-labs/plugin-serverless && npm run promote
